### ISSUE TITLE
Installation fail even with sudo (permission denied)

### ISSUE THREAD

**Issue by gagarine** [arunvelsriram/docker-time-sync-agent#2]
> ➜  ~ sudo curl https://raw.githubusercontent.com/arunvelsriram/docker-time-sync-agent/master/install.sh | bash
> Password:
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  1174  100  1174    0     0   3511      0 --:--:-- --:--:-- --:--:--  3504
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  3643  100  3643    0     0   6400      0 --:--:-- --:--:-- --:--:--  6402
> 
> Preparing to install v1.1.0...
> 
> /tmp ~
> 
> Setting up scripts and binary files...
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   589    0   589    0     0   1122      0 --:--:-- --:--:-- --:--:--  1121
> 100  6354  100  6354    0     0   5203      0  0:00:01  0:00:01 --:--:--  5203
> Archive:  Binaries.zip
>    creating: Binaries/
>   inflating: Binaries/docker-time-sync-agent
>   inflating: Binaries/update-docker-time
> 
> Setting up Launch Agent...
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   685  100   685    0     0   4209      0 --:--:-- --:--:-- --:--:--  4202
> cp: /Users/simon/Library/LaunchAgents/io.github.arunvelsriram.docker-time-sync-agent.plist: Permission denied

**Comment by arunvelsriram** [comment]
Am suspecting the permission, owner of `~/Library/LaunchAgents`

Can you please post the output of `ls -ld ~/Library/LaunchAgents` ?

**Comment by gagarine** [comment]
```
➜  ~ ls -ld ~/Library/LaunchAgents
drwxr-xr-x  4 root  staff  136 Dec 20 12:49 /Users/simon/Library/LaunchAgents
```

It should be owned by my user?

**Comment by arunvelsriram** [comment]
Yes it should be owned by your user. The `Library/LaunchAgents` directory inside your user directory (`/Users/<your-user-name>`) is a place to hold user specific daemons/agents so I think there its not necessary to be owned by `root`.

**Comment by gagarine** [comment]
thanks. I followed https://support.apple.com/en-us/HT203538 to reset my home permission to the default. The installer then worked without a glitch.
