### ISSUE TITLE
No longer necessary pretty soon

### ISSUE THREAD

**Issue by marcelstoer** [arunvelsriram/docker-time-sync-agent#7]
Maybe you should mention that this was fixed upstream: https://github.com/docker/for-mac/issues/17#issuecomment-300734810

**Comment by arunvelsriram** [comment]
Hi @marcelstoer the issue if fixed only on edge (beta) release. Will mention as fixed once stable version is released. Closing this now.

**Comment by Miladiir** [comment]
The fix is now live if the user updated his docker installation.

**Comment by arunvelsriram** [comment]
Updated README with the status of time drift issue.
